protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends Controller {

    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * 验证规则.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
           
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array(),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function init() {
        parent::init();
    }

    public function actionIndex() {
        $this->renderPartial('index');
    }

    public function actionHeader() {
        $this->renderPartial('header');
    }

    public function actionMenu() {
        $this->renderPartial('menu');
    }

    public function actionMain() {
        $this->renderPartial('main');
    }

}

protected/modules/admin/controllers/HelpController.php
<?php

class HelpController extends Controller {

    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * 验证规则.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array(),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }
    /**
     * 清理缓存.
     * @return array access control rules
     */
    public function actionClear() {
        Yii::app()->cache->flush();
        XUtils::message('success', '缓存已经清理',  $this->createUrl('default/main'));
    }

}

protected/modules/admin/controllers/LoginController.php
<?php

class LoginController extends XAdminiBase {


    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
                'maxLength' => '4',
                'minLength' => '4',
            ),
            array('allow',
                'actions' => array('captcha'),
                'users' => array('*'),
            ),
        );
    }

    //登陆验证
    public function actionIndex() {
        $model = new LoginForm;
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];

            if ($model->validate() && $model->login()) {
                Yii::app()->session['logintime'] = time();
                $this->redirect(array('/admin/default/index'));
            }
        }
        $this->renderPartial('index', array('model' => $model));
    }

    public function actionLogoout() {
        Yii::app()->user->logout();
        $this->redirect($this->createUrl('login/index'));
    }

}

protected/modules/admin/controllers/OptionController.php
<?php

class OptionController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * 验证规则.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Option;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Option']))
		{
			$model->attributes=$_POST['Option'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Option']))
		{
			$model->attributes=$_POST['Option'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Option');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Option('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Option']))
			$model->attributes=$_GET['Option'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Option::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='option-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * 验证规则.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk((int)$id);
                //$model->pwd = '';
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/views/default/header.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<LINK href="<?php echo Yii::app()->request->baseUrl ?>/css/admin.css" type="text/css" rel="stylesheet">
</HEAD>
<BODY>
<TABLE cellSpacing=0 cellPadding=0 width="100%" 
background="<?php echo Yii::app()->request->baseUrl ?>/images/header_bg.jpg" border=0>
  <TR height=56>
    <TD width=260><IMG height=56 src="<?php echo Yii::app()->request->baseUrl ?>/images/header_left.jpg" 
    width=260></TD>
    <TD style="FONT-WEIGHT: bold; COLOR: #fff; PADDING-TOP: 20px" 
      align=middle>当前用户：admin &nbsp;&nbsp; <a style="COLOR: #fff" 
      href="" 
      target=main>修改口令</a> &nbsp;&nbsp; <a style="COLOR: #fff" 
      onclick="if (confirm('确定要退出吗？')) return true; else return false;" 
      href="<?php echo $this->createUrl('login/logoout');?>" target=_top>退出系统</a> 
    </TD>
   
    <TD align=right width=268><IMG height=56 
      src="<?php echo Yii::app()->request->baseUrl ?>/images/header_right.jpg" width=268></TD></TR></TABLE>
<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
  <TR bgColor=#1c5db6 height=4>
    <TD></TD></TR></TABLE></BODY></HTML>

protected/modules/admin/views/default/index.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Frameset//EN">
<HTML>
<HEAD>
<TITLE>管理中心 V1.0</TITLE>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<META http-equiv=Pragma content=no-cache>
<META http-equiv=Cache-Control content=no-cache>
<META http-equiv=Expires content=-1000>
<link  rel="shortcut icon"  href="<?php echo Yii::app()->request->baseUrl ?>/images/favicon.ico">
<LINK href="<?php echo Yii::app()->request->baseUrl ?>/css/admin.css" type="text/css" rel="stylesheet">
</HEAD>
<FRAMESET border=0 frameSpacing=0 rows="60, *" frameBorder=0>
    <FRAME name=header src="<?php echo $this->createUrl('/admin/default/header');?>" frameBorder=0 noResize scrolling=no>
<FRAMESET cols="170, *">
    <FRAME name=menu src="<?php echo $this->createUrl('/admin/default/menu');?>" scrolling="no" frameBorder=0 noResize>
<FRAME name=main src="<?php echo $this->createUrl('/admin/default/main');?>" frameBorder=0 noResize scrolling=yes>
</FRAMESET>
</FRAMESET>
<noframes>
</noframes>
</HTML>

protected/modules/admin/views/default/main.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<LINK href="<?php echo Yii::app()->request->baseUrl; ?>/css/admin.css" type="text/css" rel="stylesheet">
</HEAD>
<BODY>
<TABLE cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
  <TR height=28>
    <TD background=<?php echo Yii::app()->request->baseUrl; ?>/images/title_bg1.jpg>当前位置: </TD></TR>
  <TR>
    <TD bgColor=#b1ceef height=1></TD></TR>
  <TR height=20>
    <TD background=<?php echo Yii::app()->request->baseUrl; ?>/images/shadow_bg.jpg></TD></TR></TABLE>
<TABLE cellSpacing=0 cellPadding=0 width="90%" align=center border=0>
  <TR height=100>
    <TD align=middle width=100><IMG height=100 src="<?php echo Yii::app()->request->baseUrl; ?>/images/admin_p.gif" 
      width=90></TD>
    <TD width=60>&nbsp;</TD>
    <TD>
      <TABLE height=100 cellSpacing=0 cellPadding=0 width="100%" border=0>
        
        <TR>
          <TD>当前时间：2008-12-27 17:03:55</TD></TR>
        <TR>
          <TD style="FONT-WEIGHT: bold; FONT-SIZE: 16px">admin</TD></TR>
        <TR>
          <TD>欢迎进入网站管理中心！</TD></TR></TABLE></TD></TR>
  <TR>
    <TD colSpan=3 height=10></TD></TR></TABLE>
<TABLE cellSpacing=0 cellPadding=0 width="95%" align=center border=0>
  <TR height=20>
    <TD></TD></TR>
  <TR height=22>
    <TD style="PADDING-LEFT: 20px; FONT-WEIGHT: bold; COLOR: #ffffff" 
    align=middle background=<?php echo Yii::app()->request->baseUrl; ?>/images/title_bg2.jpg>您的相关信息</TD></TR>
  <TR bgColor=#ecf4fc height=12>
    <TD></TD></TR>
  <TR height=20>
    <TD></TD></TR></TABLE>
<TABLE cellSpacing=0 cellPadding=2 width="95%" align=center border=0>
  <TR>
    <TD align=right width=100>登陆帐号：</TD>
    <TD style="COLOR: #880000">admin</TD></TR>
  <TR>
    <TD align=right>真实姓名：</TD>
    <TD style="COLOR: #880000">admin</TD></TR>
  <TR>
    <TD align=right>注册时间：</TD>
    <TD style="COLOR: #880000">2007-7-25 15:02:04</TD></TR>
  <TR>
    <TD align=right>登陆次数：</TD>
    <TD style="COLOR: #880000">58</TD></TR>
  <TR>
    <TD align=right>上线时间：</TD>
    <TD style="COLOR: #880000">2008-12-27 17:02:54</TD></TR>
  <TR>
    <TD align=right>IP地址：</TD>
    <TD style="COLOR: #880000">222.240.172.117</TD></TR>
  <TR>
    <TD align=right>身份过期：</TD>
    <TD style="COLOR: #880000">30 分钟</TD></TR>
  <TR>
    <TD align=right>网站开发QQ：</TD>
    <TD style="COLOR: #880000">215288671</TD></TR>
  <TR>
    <TD align=right>免费模板网：</TD>
    <TD style="COLOR: #880000"><a href="http://www.865171.cn">www.865171.cn</a></TD></TR></TABLE></BODY></HTML>

protected/modules/admin/views/default/menu.php
<!DOCTYPE HTML PUBLIC "-//W3C//Dtd HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<LINK href="<?php echo Yii::app()->request->baseUrl ?>/css/admin.css" type="text/css" rel="stylesheet">
<SCRIPT language=javascript>
	function expand(el)
	{
		childObj = document.getElementById("child" + el);

		if (childObj.style.display == 'none')
		{
			childObj.style.display = 'block';
		}
		else
		{
			childObj.style.display = 'none';
		}
		return;
	}
</SCRIPT>
</HEAD>
<BODY>
<table height="100%" cellSpacing=0 cellPadding=0 width=170 
background=<?php echo Yii::app()->request->baseUrl ?>/images/menu_bg.jpg border=0>
  <tr>
    <td vAlign=top align=middle>
      <table cellSpacing=0 cellPadding=0 width="100%" border=0>
        
        <tr>
          <td height=10></td></tr></table>
      <table cellSpacing=0 cellPadding=0 width=150 border=0>
        
        <tr height=22>
          <td style="PADDING-LEFT: 30px" background=<?php echo Yii::app()->request->baseUrl ?>/images/menu_bt.jpg><A 
            class=menuParent onclick=expand(1) 
            href="javascript:void(0);">帐户管理</A></td></tr>
        <tr height=4>
          <td></td></tr></table>
      <table id=child1 style="DISPLAY: none" cellSpacing=0 cellPadding=0 
      width=150 border=0>
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('user/admin');?>" 
            target=main>查看帐户</A></td></tr>
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('user/create');?>" 
            target=main>添加帐户</A></td></tr>
      
        <tr height=4>
          <td colSpan=2></td></tr></table>
      <table cellSpacing=0 cellPadding=0 width=150 border=0>
        <tr height=22>
          <td style="PADDING-LEFT: 30px" background=images/menu_bt.jpg><A 
            class=menuParent onclick=expand(2) 
            href="javascript:void(0);">内容管理</A></td></tr>
        <tr height=4>
          <td></td></tr></table>
      <table id=child2 style="DISPLAY: none" cellSpacing=0 cellPadding=0 
      width=150 border=0>
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('content/create');?>" 
            target=main>添加链接</A></td></tr>
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('content/admin');?>" 
            target=main>查看链接</A></td></tr>
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('category/create');?>" 
            target=main>添加分类</A></td></tr>
        
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('category/admin');?>" 
            target=main>查看分类</A>
          </td>
        </tr>
        
         <tr height=4>
          <td colSpan=2></td></tr></table>
        
    <table cellSpacing=0 cellPadding=0 width=150 border=0>
        
        <tr height=22>
          <td style="PADDING-LEFT: 30px" background=<?php echo Yii::app()->request->baseUrl ?>/images/menu_bt.jpg><A 
            class=menuParent onclick=expand(3) 
            href="javascript:void(0);">碎片管理</A></td></tr>
        <tr height=4>
          <td></td>
        </tr>
    </table>
      <table id=child3 style="DISPLAY: none" cellSpacing=0 cellPadding=0 
      width=150 border=0>
          <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('option/create');?>" 
            target=main>添加碎片</A>
          </td>
        </tr>
          
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('option/admin');?>" 
            target=main>查看碎片</A>
          </td>
        </tr>
        
      
        <tr height=4>
          <td colSpan=2></td>
        </tr>
      </table>     
        
        
        
        
      
    <table cellSpacing=0 cellPadding=0 width=150 border=0>
        
        <tr height=22>
          <td style="PADDING-LEFT: 30px" background=<?php echo Yii::app()->request->baseUrl ?>/images/menu_bt.jpg><A 
            class=menuParent onclick=expand(10) 
            href="javascript:void(0);">其他管理</A></td></tr>
        <tr height=4>
          <td></td>
        </tr>
    </table>
      <table id=child10 style="DISPLAY: none" cellSpacing=0 cellPadding=0 
      width=150 border=0>
        <tr height=20>
          <td align=middle width=30><IMG height=9 
            src="<?php echo Yii::app()->request->baseUrl ?>/images/menu_icon.gif" width=9></td>
          <td><A class=menuChild 
            href="<?php echo $this->createUrl('help/clear');?>" 
            target=main>清理缓存</A></td>
        </tr>
        
      
        <tr height=4>
          <td colSpan=2></td>
        </tr>
      </table> 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
      
      
      
      
     
      
      
      
      
      </td>
    <td width=1 bgColor=#d1e6f7></td></tr></table></BODY></HTML>